### ISSUE TITLE
Task from signalingClient.getRTCSessionDescriptions never returns from try await

### ISSUE THREAD

**Issue by dankelley2** [grbaczek/iOS_WebRTC_VideoChat#1]
When the following line of code:
> if let rtcSessionDescription = **try await signalingClient.getRTCSessionDescriptions(**

does not get a session description from firebase (due to the host being the first one to connect) it never returns (firebase-ios-sdk 10.14.0). This never ending await causes the **try await group.waitForAll()** to also hang indefinitely even when a timeout occurs.

Is this an issue you've seen before? Unfortunately I can't run the repo and tests without some changes because I'm on the latest ios / xCode betas, and would like to identify whether or not this issue can be reproduced outside of my environment.

Changes I've made to run on IOS 17 beta:
 * Running Xcode 15 build 8
 * Moved WebRTC from a pod to a Package dependency
 * Updated firebase-ios-sdk to 10.14.0 for updated swift compatibility
 
 Am able to successfully run a video / audio chat between an IOS 15.6 and an IOS 17 device, given that the host connects first, then the guest immediately connects within the timeout timeframe.

```
try await withThrowingTaskGroup(of: Void.self) { group in
    group.addTask {
        if let rtcSessionDescription = **try await signalingClient.getRTCSessionDescriptions**(
            currentPeer.watchKey,
            chatRoomId
        ).first(where: { _ in true }) {
            try await webRTCClient.set(remoteSdp: rtcSessionDescription)
            connectionStateContainer.info = "Remote SDP set"
            if currentPeer == .guest {
                let sdp = try await webRTCClient.answer()
                try await signalingClient.send(sdp: sdp, chatRoomId: chatRoomId, collection: currentPeer.sendKey)
                connectionStateContainer.info = "SDP answer sent"
            }
        }
    }
    if currentPeer == .host {
        group.addTask {
            let sdp = try await webRTCClient.offer()
            try await signalingClient.send(sdp: sdp, chatRoomId: chatRoomId, collection: currentPeer.sendKey)
            connectionStateContainer.info = "SDP offer sent"
        }
    }
    group.addTask {
        for _ in 1...40 {
            if webRTCClient.isRemoteDescriptionSet {
                return
            }
            try await Task.sleep(milliseconds: 100)
        }
        connectionStateContainer.info = "Connection timeout"
        throw connectionError.connectionTimeoutError
    }
    **try await group.waitForAll()**
}
```

**Comment by grbaczek** [comment]
Hi Dan. Thx for raising this issue. I am on holidays right now but I will look into it as soon as I can - some day next week

**Comment by grbaczek** [comment]
I could recreate the issue. It should be fixed now. It was due to Firebase client behaving slightly differently in the newer version. Now the snapshot listener is called even though the document is empty so the deserialisation fails. `document.exists`  fixes this issue.

```Swift
AsyncThrowingStream { continuation in
            let listener = getSpdDocument(collection, chatRoomId)
                .addSnapshotListener { documentSnapshot, error in
                    if let document = documentSnapshot, document.exists
                    {
                        do {
                            let sessionDescription: SessionDescription = try document.data(as: SessionDescription.self)
                            continuation.yield(sessionDescription.rtcSessionDescription)
                        } catch {
                            continuation.finish(throwing: error)
                        }
                    }
                }
            continuation.onTermination = { _ in
                listener.remove()
            }
        }
```

**Comment by dankelley2** [comment]
Nice catch! I didn’t know that document.exists property existed. Thanks for the fix and for teaching me something new!
