### ISSUE TITLE
Stun server No route to host with host 

### ISSUE THREAD

**Issue by Goule** [grbaczek/iOS_WebRTC_VideoChat#3]
Hello,

I'm trying the sample project, but I'm facing with some issue after creating the room : 

`
(stun_port.cc:604): UDP send of 20 bytes to host stun3.l.google.com:19302 (142.251.125.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun2.l.google.com:19302 (64.233.164.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun.l.google.com:19302 (173.194.76.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun4.l.google.com:19302 (74.125.27.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun1.l.google.com:19302 (142.251.27.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun.l.google.com:19302 (173.194.76.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun2.l.google.com:19302 (64.233.164.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun1.l.google.com:19302 (142.251.27.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun4.l.google.com:19302 (74.125.27.x:19302) failed with error 0 : [0x00000041] No route to host
(stun_port.cc:604): UDP send of 20 bytes to host stun3.l.google.com:19302 (142.251.125.x:19302) failed with error 0 : [0x00000041] No route to host
`

The room is well created in Firebase, "SDP offer sent" is well displayed on the screen. But after some seconds "Connection timeout" is displayed. It looks like the stun servers are not available ? Or maybe I don't understand the WebRTC step? 

Tested on wifi or LTE network and no VPN

In any case thanks for this very well-explained repository which allows us to understand webrtc well! :)

**Comment by grbaczek** [comment]
Hi, @Goule . It has been some time since this repo was updated maybe stun/turn servers aren't available. I will investigate it.

**Comment by Goule** [comment]
Thanks @grbaczek!

**Comment by grbaczek** [comment]
Try pulling the recent version of the code. I fixed a bug experienced while reestablishing the connection.

I tested the app - worked fine on my devices. 

Google STUN servers are used. You need TURN server if one of the devices is behind firewall - make sure both of your devices are on the same network.

There could be an issue with your signalling server - I created a new branch: `working_signaling_server` with my firebase signalling server against which I've just tested the app. Try testing with this [branch](https://github.com/grbaczek/iOS_WebRTC_VideoChat/tree/feature/working_signaling_server) 

PS. Remember to star the repo if it helped you in anyway 😉

**Comment by Goule** [comment]
Soon good, there was an issue on my side with my router and some restrictions! 

Done for the star :)
