### ISSUE TITLE
Poor resolution and framerate

### ISSUE THREAD

**Issue by floriangbh** [grbaczek/iOS_WebRTC_VideoChat#4]
Hello, 

Firstly, thanks for this project! 

After some tests with the demo project, I'm facing to a quality issue. After some seconds of video, the quality drops and some frames drop. 
I've identified these logs : 
```
(probe_controller.cc:346): Detected big bandwidth drop, start probing.
<...>
Dropping frame. Too large for target bitrate.
```

I've tested this project https://github.com/stasel/WebRTC-iOS with a local signaling server, and the video quality is great, with no resolution or fps issue. The weird thing is it seems to be the same WebRTC management, only the signaling server differs.

Have you any idea of which is the issue ? 

Thanks 
Best

**Comment by grbaczek** [comment]
Hi Florian

thx for heads up. I have not noticed anything like this. This sounds really weird. Video quality should have nothing to do with signalling server. 

I will give it a try and see if I can reproduce what you're experiencing.

**Comment by floriangbh** [comment]
This morning everything is fine... I was on coworking space with a lot of people yesterday, maybe there was poor local network quality and an issue!
